<?php

/*
 * Implementation of hook_form_alter()
 */
function view_match_report_filter_form_alter(&$form, &$form_state, $form_id)
{
  // dpm($form);

  // if (true) {
  //   # code...
  // }
}


/*
 * Implementation of hook_form_alter()
 */
function view_match_report_filter_views_query_alter(&$view, &$query)
{

  dpm($view);
  //$query->where[1]['conditions'][2]['value'][':field_data_field_year_date_field_year_date_value'] = 2016;
}